# Generated by Django 5.0 on 2023-12-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauthenticationapp', '0005_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
