# Generated by Django 5.0 on 2023-12-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauthenticationapp', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
